#!/usr/bin/zsh

SECTION_NAME=alexia-auth

if ! tmux has-session -t $SECTION_NAME; then
  tmux new -s $SECTION_NAME -d

  tmux split-window -t $SECTION_NAME:1 -h
  tmux split-window -t $SECTION_NAME:1 -v

  tmux send-keys -t $SECTION_NAME:1.0 \
    cd\ ~/workspace/alexia/autenticacao Enter
  tmux send-keys -t $SECTION_NAME:1.0 \
    nvim Enter

  tmux send-keys -t $SECTION_NAME:1.1 \
    cd\ ~/workspace/alexia/autenticacao Enter
  tmux send-keys -t $SECTION_NAME:1.1 \
    docker-compose\ up Enter

  tmux send-keys -t $SECTION_NAME:1.2 \
    cd\ ~/workspace/alexia/autenticacao Enter
fi
tmux attach -t $SECTION_NAME
