#!/usr/bin/zsh

SESSION_NAME=solus

if ! tmux has-session -t $SESSION_NAME; then
  tmux new -s $SESSION_NAME -d

  tmux new-window -t $SESSION_NAME:2

  tmux send-keys -t $SESSION_NAME:1 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t $SESSION_NAME:1 \
    nvim Enter

  tmux send-keys -t $SESSION_NAME:2 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t $SESSION_NAME:2 \
    make\ dev Enter
fi
tmux attach -t $SESSION_NAME
