#!/usr/bin/zsh

if ! tmux has-session -t solus; then
  tmux new -s solus -d

  tmux new-window -t solus:2

  tmux send-keys -t solus:1 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t solus:1 \
    nvim Enter

  tmux send-keys -t solus:2 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t solus:2 \
    make\ dev Enter
fi
tmux attach -t solus
