#!/usr/bin/zsh

SESSION_NAME=solus

if ! tmux has-session -t $SESSION_NAME; then
  tmux new -s $SESSION_NAME -d

  tmux split-window -t $SESSION_NAME:1 -h

  tmux send-keys -t $SESSION_NAME:1.0 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t $SESSION_NAME:1.0 \
    nvim Enter

  tmux send-keys -t $SESSION_NAME:1.1 \
    cd\ ~/workspace/solus/frontend Enter
  tmux send-keys -t $SESSION_NAME:1.1 \
    make\ dev Enter
fi
tmux attach -t $SESSION_NAME
